<?php
if (isset($_POST['submitbtn'])) {
    echo '<pre>';
    print_r($_POST);
    echo '</pre>';
    die;
}


echo $this->getHtmlField('formstart', ['action' => '', 'method' => 'post', 'id' => 'id0', 'class' => 'fromclass', 'enctype' => 'multipart/form-data']);
echo $this->getHtmlField('text', ['id' => 'id1', 'class' => 'one two three', 'name' => 'catlog_product[name]', 'placeholder' => 'name', 'value' => '']);
echo $this->getHtmlField('number', ['id' => 'id2', 'class' => 'one two three', 'name' => 'catlog_product[id]', 'placeholder' => 'id', 'value' => '']);
echo $this->getHtmlField('email', ['id' => 'id4', 'class' => 'one two three', 'name' => 'catlog_product[email]', 'value' => '']);
echo $this->getHtmlField('password', ['id' => 'id5', 'class' => 'one two three', 'name' => 'catlog_product[pass]', 'value' => '']);
echo $this->getHtmlField('file', ['id' => 'id6', 'class' => 'one two three', 'name' => 'catlog_product[file]', 'value' => '']);
echo $this->getHtmlField('color', ['id' => 'id7', 'class' => 'one two three', 'name' => 'catlog_product[color]', 'value' => '']);
echo $this->getHtmlField('date', ['id' => 'id8', 'class' => 'one two three', 'name' => 'catlog_product[date]', 'value' => '']);
echo $this->getHtmlField('textarea', ['id' => 'id9', 'class' => 'one two three', 'name' => 'catlog_product[textarea]', 'value' => '']);
echo $this->getHtmlField('range', ['id' => 'id10', 'class' => 'one two three', 'name' => 'catlog_product[range]', 'value' => '0', 'min' => '0', 'max' => '5', 'step' => '0.5']);
echo $this->getHtmlField('radio', ['id' => 'id11', 'class' => 'one two three', 'name' => 'catlog_product[radio]', 'value' => '1']);
echo $this->getHtmlField('lable', ['for' => 'id11', 'value' => '1']);
echo $this->getHtmlField('radio', ['id' => 'id12', 'class' => 'one two three', 'name' => 'catlog_product[radio]', 'value' => '2']);
echo $this->getHtmlField('lable', ['for' => 'id12', 'value' => '2']);
echo $this->getHtmlField('radio', ['id' => 'id13', 'class' => 'one two three', 'name' => 'catlog_product[radio]', 'value' => '3']);
echo $this->getHtmlField('lable', ['for' => 'id13', 'value' => '3']);
echo $this->getHtmlField('checkbox', ['id' => 'id14', 'class' => 'one two three', 'name' => 'catlog_product[check][]', 'value' => 'one']);
echo $this->getHtmlField('lable', ['for' => 'id14', 'value' => 'one']);
echo $this->getHtmlField('checkbox', ['id' => 'id15', 'class' => 'one two three', 'name' => 'catlog_product[check][]', 'value' => 'two']);
echo $this->getHtmlField('lable', ['for' => 'id15', 'value' => 'two']);
echo $this->getHtmlField('checkbox', ['id' => 'id16', 'class' => 'one two three', 'name' => 'catlog_product[check][]', 'value' => 'three']);
echo $this->getHtmlField('lable', ['for' => 'id16', 'value' => 'three']);
echo $this->getHtmlField('dropdown', ['id' => 'id3', 'class' => 'one two three', 'name' => 'catlog_product[select]', 'options' => ['--select--' => 'default', 'ten' => '10', 'twenty ' => '20', 'thirty' => '30']]);
echo $this->getHtmlField('submit', ['id' => 'id3', 'class' => 'one two three', 'name' => 'submitbtn', 'value' => 'submit']);
echo $this->getHtmlField('formend', []);